name: Lint & Test

on:
  push:
    branches:
      - '**'
      - '!master'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Linter
        run: npm run lint
